branch-defaults:
  takePhoto:
    environment: crime-loud-dev
global:
  application_name: crime_loud
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
